# Generated by Django 3.1.5 on 2021-03-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
