# Generated by Django 3.1.5 on 2021-03-15 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_listing_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='businessMan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nombre',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passkey',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='highestBidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Bidder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='publisher',
            field=models.CharField(default='seller', max_length=64),
            preserve_default=False,
        ),
    ]
